# Generated by Django 3.1.7 on 2021-04-20 12:05

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=catalog.models.generate_unique_product_code, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('details', models.TextField(default=' ', max_length=300)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.UUIDField(default=catalog.models.generate_unique_item_code, editable=False, primary_key=True, serialize=False)),
                ('size', models.CharField(default='Unavailable', max_length=30)),
                ('num_available', models.IntegerField(default=1)),
                ('num_sold', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=30)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
    ]
