# Generated by Django 3.1.7 on 2021-04-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210420_0807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cat_id',
            new_name='cat',
        ),
        migrations.AddField(
            model_name='category',
            name='cat_name',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
