# Generated by Django 3.1.7 on 2021-04-20 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_is_available'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('size', 'color')},
        ),
    ]
