# Generated by Django 3.1.7 on 2021-04-20 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210420_1704'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('product', 'size', 'color')},
        ),
    ]
