# Generated by Django 3.1.7 on 2021-04-21 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20210420_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='catalog.category'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('category_name', 'parent')},
        ),
    ]
