# Generated by Django 3.1.7 on 2021-04-21 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20210420_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_child',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(limit_choices_to={'is_child': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='catalog.category'),
        ),
    ]
