# Generated by Django 3.1.7 on 2021-04-21 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20210420_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(limit_choices_to={'is_child': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='catalog.category'),
        ),
    ]
