# Generated by Django 3.1.7 on 2021-04-21 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20210420_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='num_available',
        ),
        migrations.RemoveField(
            model_name='item',
            name='num_sold',
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(limit_choices_to={'is_child': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(limit_choices_to={'is_child': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='catalog.category'),
        ),
    ]
