# Generated by Django 3.1.7 on 2021-04-25 14:35

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=' ', max_length=30)),
                ('description', models.TextField(default=' ', max_length=150)),
                ('is_child', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'is_child': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=products.models.generate_unique_product_code, editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('details', models.TextField(default=' ', max_length=600)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brand', to='products.brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('sub_category', models.ForeignKey(limit_choices_to={'is_child': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=products.models.generate_unique_code, editable=False, primary_key=True, serialize=False, unique=True)),
                ('size', models.CharField(default='Unavailable', max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('is_available', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
