# Generated by Django 3.1.7 on 2021-04-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='num_available',
            field=models.IntegerField(default=1),
        ),
    ]
