# Generated by Django 3.1.7 on 2021-04-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_item_num_available'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('product', 'size', 'color')},
        ),
    ]
