# Generated by Django 3.1.7 on 2021-06-08 21:34

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_remove_cartitem_item'),
        ('orders', '0002_remove_orderitem_item'),
        ('products', '0004_auto_20210608_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.UUIDField(default=products.models.generate_unique_code, editable=False, primary_key=True, serialize=False, unique=True)),
                ('num_available', models.IntegerField(default=1)),
                ('is_available', models.BooleanField(default=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='size',
            unique_together={('name', 'value')},
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='variant',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.size'),
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('product', 'size', 'color')},
        ),
    ]
