# Generated by Django 3.1.7 on 2021-06-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210608_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(default='slug', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='color',
            unique_together={('name',)},
        ),
    ]
