# Generated by Django 3.1.7 on 2021-06-09 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210609_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='num_available',
            new_name='quantity',
        ),
    ]
