# Generated by Django 3.1.7 on 2021-06-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210609_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_root',
            field=models.BooleanField(default=False),
        ),
    ]
