# Generated by Django 3.1.7 on 2021-06-10 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_is_root'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_root',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.DeleteModel(
            name='CategoryRelationship',
        ),
    ]
