# Generated by Django 3.1.7 on 2021-06-08 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210608_1734'),
        ('orders', '0002_remove_orderitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.variant'),
            preserve_default=False,
        ),
    ]
