# Generated by Django 3.1.7 on 2021-03-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_on_email_list',
            field=models.BooleanField(default=False),
        ),
    ]
